tasks:
  - init: |
      pip install fastapi
      gp sync-done installation
    command: pip install uvicorn
  - init: gp sync-await installation
    command: uvicorn app.main:app --reload  
#  - name: Start web server
#    init: python -m http.server 8000

#ports:
#  - port: 8000
#    onOpen: open-preview
