tasks:
  - init: gp sync-done installation
    command: python -m pip install fastapi
  - init: |
      gp sync-await installation
      python -m pip install uvicorn
    command: uvicorn app.main:app --reload 
