tasks:
  - init: python -m pip install
    command: python -m pip install fastapi
  - init: |
      python -m pip install
      python -m pip install uvicorn
   command: uvicorn app.main:app --reload 
